services:
  t_db:
    container_name: tarantool_db_2
    build:
      dockerfile: Dockerfile
    volumes:
      - ./tmp/db:/var/lib/tarantool
      - ./lua-app:/etc/tarantool/instances.enabled/app
    ports:
      - "3302:3302"
      - "3301:3301"