services:
  t_db:
    container_name: tarantool_db_2
    build:
      dockerfile: Dockerfile
    volumes:
      - ./tmp/db:/var/lib/tarantool/sys_env/app
      - ./lua-app:/etc/tarantool/instances.enabled/app
    ports:
      - "3307:3316"
      - "3305:3315"
      - "3304:3314"
      - "3303:3313"
      - "3302:3302"
      - "3301:3301"
    network_mode: bridge