credentials:
  users:
    sampleuser:
      password: '123456'
      roles: [super]
      privileges:
        - permissions: [ read, write ]
          spaces: [ bands ]
        - permissions: [ execute ]
          functions: [ get_bands_older_than ]

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-002:
            iproto:
              listen:
                - uri: '0.0.0.0:3302'
app:
  file: 'myapp.lua'