credentials:
  users:
    sampleuser:
      password: '123456'
      privileges:
        - permissions: [ read, write ]
          spaces: [ bands ]
        - permissions: [ execute ]
          functions: [ get_bands_older_than ]

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001:
            iproto:
              listen:
                - uri: '127.0.0.1:3302'
app:
  file: 'myapp.lua'